notifications: 
  email:
    recipients:
      - dr.sebastian.koehler@gmail.com
      - peter.robinson@charite.de
      # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

install:
  - wget -i src/owltools/urls.txt
  
before_script:  
  - mkdir -p owltools_folder
  - mv owltools owltools_folder/
  - mv *jar owltools_folder/
  - mv ontology-rel* owltools_folder/
  - chmod +x owltools_folder/*
  - export PATH="$PATH":`pwd`/owltools_folder/
  - export OORT_ARGS='--catalog-xml catalog-v001.xml' 

script:
  - cd src/ontology/
  - make &> log.txt
  - tail -n 100 log.txt

