notifications: 
  email:
    recipients:
      - dr.sebastian.koehler@gmail.com
      - phenotype-ontologies-editors@googlegroups.com
      # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

env:
  global:
    - REPO="obophenotype/human-phenotype-ontology"
    - CI_HOME=`pwd`/$REPO

before_install:
  - cd $CI_HOME  
  - cd src/format/
  - make

install:
  - cd $CI_HOME  
  - wget -i src/owltools/urls.txt
  
before_script:
  - cd $CI_HOME
  - mkdir -p owltools_folder
  - mv owltools owltools_folder/
  - mv *jar owltools_folder/
  - mv ontology-rel* owltools_folder/
  - chmod +x owltools_folder/*
  - export PATH="$PATH":`pwd`/owltools_folder/
  - export OORT_ARGS='--catalog-xml catalog-v001.xml' 

script:
  - cd $CI_HOME  
  - cd src/ontology/
  - make &> log.txt
  - tail -n 100 log.txt

