notifications: 
  email:
    recipients:
      - dr.sebastian.koehler@gmail.com
      - phenotype-ontologies-editors@googlegroups.com
      # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

before_install:
  - pwd
  - cd src/format/
  - make

install:
  - cd ~
  - wget -i src/owltools/urls.txt
  
before_script:
  - cd ~
  - mkdir -p owltools_folder
  - mv owltools owltools_folder/
  - mv *jar owltools_folder/
  - mv ontology-rel* owltools_folder/
  - chmod +x owltools_folder/*
  - export PATH="$PATH":`pwd`/owltools_folder/
  - export OORT_ARGS='--catalog-xml catalog-v001.xml' 

script:
  - cd ~
  - cd src/ontology/
  - make &> log.txt
  - tail -n 100 log.txt

